---
title: "R Notebook"
output: html_notebook
---


```{r}
library(wisdotcrashdatabase)
library(tidyverse)
# old and new cntycode
file_loc = "C:/CSV/csv_from_sas/fst/"
```

```{r}
crash <- import_db_data(file_loc, "crash", years_old = c("16"), years = c("17"), columns = c("RLTNTRWY", "CRSHLOC", "INTTYPE", "INTDIS", "CRSHTIME"))

crash %>% get_crash_times(combine_with_old = TRUE) %>% 
  select(CRSHTIME, CRSHTIME_GROUP, newtime ,CRSHDATE, newtime_old) %>% 
  filter(lubridate::year(CRSHDATE) == 2016, is.na(newtime))

lis=crash$CRSHTIME_GROUP %>% unique()
```

```{r}
person <- import_db_data(file_loc, "person", years_old = c("16"), years = c("17"), columns = c("AGE"))

get_age_groups(person) %>% select(AGE,age_group_5yr )
age_group_5yr <- function(person_df, age_column = "AGE") {
  person_df <- person_df %>% dplyr::mutate(age_group_5yr = cut(
    # add age_group column, 5 year intervals
    .data[[age_column]],
    right = FALSE,
    c(0, 4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 120),
    labels = c(
      "0-4",
      "5-9",
      "10-14",
      "15-19",
      "20-24",
      "25-29",
      "30-34",
      "35-39",
      "40-44",
      "45-49",
      "50-54",
      "55-59",
      "60-64",
      "65-69",
      "70+"
    ),
    include.lowest = T
  ))
  # Get levels of age_group factor and add Unknown
  # levels <- levels(.data$person_df$age_group_5yr)
  # levels[length(levels) + 1] <- "UNKNOWN"
  # # refactor agegroup to include "None" as a factor level
  # # and replace NA with "None"
  # person_df$age_group_5yr <- person_df %>%
  #   factor(.data$age_group_5yr, levels = levels)
  # .data$person_df$age_group_5yr[is.na(.data$person_df$age_group_5yr)] <-
  #   "UNKNOWN"
  person_df
}
```
```{r}

year1=as.character(seq(88, 99,  1))
year2=formatC(seq(00, 16, 1), digits = 0, width = 2, format = "f", flag = "0")
year1
year2

get_list_of_years <- function(start_year = "94",
                              end_year = "27") {
  # between 1985 and 2030
  if (start_year > 85 & end_year < 30) {
    year1 = as.character(seq(start_year, 99,  1))
    year2 = formatC(
      seq(00, end_year, 1),
      digits = 0,
      width = 2,
      format = "f",
      flag = "0"
    )
    return(c(year1, year2))
    # between 1985 and 1999
  } else if (start_year > 85 & end_year <= 99) {
    return(as.character(seq(start_year, end_year,  1)))
  } # between 2000 and 2030
  else if (start_year >= 0 & end_year < 30) {
    return(formatC(seq(start_year, end_year, 1), digits = 0, width = 2, format = "f", flag = "0"))
  }
}

get_list_of_years("89", "89")
```

